# Continuous Integration pipeline
name: CI 

# Run on pushes to main/dev and PRs
on:
  push:
    branches: [ main, dev ]   
  pull_request:
    branches: [ dev ]        


# Runner
jobs:
  lint-and-bdd:
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
           pip install -r requirements.txt

      # Style/syntax issues
      - name: Lint (flake8)
        run: flake8 .  

      # Saves test reports
      - name: Behave (BDD)
        run: |
          mkdir -p reports         # JUnit XML
          behave --junit --junit-directory reports

      - name: Upload BDD reports
        uses: actions/upload-artifact@v4
        with:
          name: bdd-reports
          path: reports